// The Number and Title for the TD should be the number and title of the GitHub Issue that was generated for this problem, question, etc. that resulted
// in this TD being generated
= DSC0001 - Additional Workload Options in FCS_COP.1/PBKDF
:showtitle:
:imagesdir: images
:icons: font
:revnumber: 1
// revdate should be the date of the revision of this version of the TD
:revdate: 2022-12-16
:linkattrs:

:iTC-longname: Hardcopy Device
:iTC-shortname: HCD-iTC
:iTC-email: iTC-HCD@niap-ccevs.org
:iTC-website: https://hcd-iTC.github.io/
// Provide the link here to either the HCD cPP and/or the HCD SD as applicable
:iTC-GitHub: https://github.com/HCD-iTC/cPP/

Published: {revdate}

== Impacted Documents
link:https://hcd-itc.github.io/cPP/cPP_HCD_V1.0.pdf

link:https://hcd-itc.github.io/SD/SD_HCD_V1.0.pdf

// Reference the applicable HCD cPP SFR(s) / SARs or HCD SD Assurace Activities that this TD pertains to
== References
FCS_COP.1/PBKDF

// Provide the issue description extracted from the Issue that was generated for this problem, question, etc. that resulted in this TD being generated
== Issue Description
The FCS_COP.1/PBKDF requirement provides only a single method for ensuring the workload necessary to by requiring at least 1000 iterations of a PBKDF function. There are additional methods for ensuring a sufficient workload equivalent to the 1000 PBKDF iterations that should be allowed.

// Provide the resolution agreed upon by the HIT for this Issue
== Resolution
The FCS_COP.1/PBKDF requirement mandates a specific implementation to thwart brute force attacks on the DSC. As there are many different approaches that can be used to thwart such attacks, the cPP and SD will be updated to be less prescriptive in the implementation details while providing equivalent strength in terms of the workload required.

// Provide below each specific change that is to be made to the HCD cPP nad/or HCD SD by Section number, paragraph and line to resolve this issue
=== CPP_DSC_v1.0
FCS_COP.1/PBKDF is modified as follows (yellow highlights for additions, strikethrough for deletions):

FCS_COP.1.1/PBKDF:: The TSF shall perform [_password-based key derivation functions_] in accordance with a specified cryptographic algorithm [_HMAC-[selection: SHA-256, SHA-384, SHA-512]_ ], *with #[selection:# _[assignment: integer number greater than or equal to 1000 #iterations], at least 1 iteration followed by a function equivalent to the workload of at least 1000# [.line-through]#]# iterations_#]#, and output* cryptographic key sizes [selection: 128, 192, 256] bits that meet the following standard: [_NIST SP 800-132_].

_Application Note 50_:: _The [.line-through]#ST# #TSF# must condition a password into a string of bits prior to using it as input to algorithms that form SKs and KEKs. The [.line-through]#ST# #TSF# can perform conditioning using one of the identified hash functions or the process described in NIST SP 800-132; the ST author selects the method used. NIST SP 800-132 requires the use of a pseudo-random function (PRF) consisting of HMAC with an approved hash function._
+
_Appendix A of NIST SP 800-132 recommends setting the iteration count in order to increase the computation needed to derive a key from a password and, therefore, increase the workload of performing a dictionary attack._
+
_The TOE must claim this requirement if it claims FCS_CKM.1/SK and selects an algorithm in the PBK row or claims FCS_CKM_EXT.5 and selects at least one of [.underline]#KeyDrv4#, [.underline]#KeyDrv5#, or [.underline]#KeyDrv6# AND uses password-based key derivation to create at least one of the inputs._
+
_#If less than 1000 PBKDF iterations are used, the ST must specify the workload equivalence to at least 1000 PBKDF iterations.#_

=== SD_DSC_v1.0
Section 4.1.3.1 is updated as follows (yellow highlights for additions, strikethrough for deletions):

*4.1.3.1.1 TSS*

The evaluator shall review the TSS to verify that it contains a description of the PBKDF. The evaluator shall also confirm the [.line-through]#ST# #TSF# supports the selected hash function itself. The evaluator shall confirm that the TSS contains a description of how the TOE ensures that the output of the PBKDF is at least the same length as that specified in FCS_CKM.1/SK and for the KeyDrv4, KeyDrv5, or KeyDrv6 in FCS_CKM_EXT.5.

#If the ST claims iterations less than 1000 iterations, the evaluator shall verify the TSS contains a description of the workload function used to claim equivalence to at least 1000 iterations of PBKDF.#

If the [.line-through]#ST# #TSF# performs additional conditioning, whitening, or manipulation of the password or passphrase before applying the PBKDF, or to the output of the PBKDF, the evaluator shall ensure that the TSS describes the actions and provides assurance that the TSF does not negatively impact the entropy of the PBKDF output.

If any manipulation of the key is performed in forming the submask that will be used to form the KEK, that process shall be described in the TSS.

*4.1.3.1.2 AGD*

There are no AGD evaluation activities for this component.

*4.1.3.1.3 Test*

No explicit testing of the formation of the submask from the input password is required. 

For the NIST SP 800-132-based conditioning of the passphrase, the required evaluation activities will be performed when doing the evaluation activities for the appropriate requirements (FCS_COP.1/HMAC).

The evaluator shall verify that the iteration count for PBKDFs performed by the TOE comply with NIST SP 800-132 by ensuring that the TSS contains a description of the estimated time required to derive key material from passwords and how the TOE increases the computation time for password-based key derivation (including but not limited to increasing the iteration count).

*4.1.3.1.4 KMD*

[.line-through]#There are no KMD evaluation activities for this component.#

#If the ST claims less than 1000 PBKDF iterations, the evaluator shall verify the KMD contains a description of the process for increasing the workload. The description shall provide a flow diagram of the operations involved including the keys used in the operations. The evaluator shall also confirm that the TSF supports any algorithms in use for this sequence of operations.#

#The KMD shall include an equivalency argument comparing the workload (time to completion) using at least 1000 PBKDF iterations vs the workload of the alternative process.#


== Tracking
https://ccusersforum.onlyoffice.com/Products/Projects/TMDocs.aspx?prjID=544859#3238373
